/*TORLETTI LARA AGOSTINA - RESOLUCIÓN DE PROBLEMAS POR COMPUTADORA - IMPLEMENTANDO FUNCIONES CON MATRICES - 13/03/2023*/
//DECLARACIÓN DE CONSTANTES Y LIBRERÍA

//CONSTANTS
#define DIM 2

//LIBRARIES
#include <stdio.h>
#include <math.h>